"""
Orchestrated upstream workflow for GROMACS + VMD + MM/PBSA + PCA.
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import shlex
import subprocess
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Tuple

import yaml

from ..pipeline.upstream import generate_upstream_scripts

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
logger = logging.getLogger(__name__)


DEFAULT_MMPBSA_IN = """\
Input file generated by gmx_MMPBSA (workflow default)

&general
  sys_name             = "{sys_name}"
  startframe           = 1
  interval             = 1
  temperature          = 310
  interaction_entropy  = 1
  ie_segment           = 25
  c2_entropy           = 1
  solvated_trajectory  = 1
  verbose              = 1
  PBRadii              = 3
/

&gb
  igb                  = 5
  saltcon              = 0.154
/

&decomposition
  idecomp              = 2
  dec_verbose          = 2
  print_res            = "within 10"
  csv_format           = 1
/
"""


@dataclass
class SystemConfig:
    name: str
    workdir: Path
    ligand_resname: str
    topology_for_vmd: str = "step3_input.psf"
    structure_gro: str = "step5_production.gro"
    structure_tpr: str = "step5_production.tpr"
    topology_top: str = "topol.top"
    trajectory_patterns: List[str] = field(
        default_factory=lambda: [
            "step5_*.xtc",
            "step5_production*.xtc",
            "prod*.xtc",
        ]
    )
    trjcat_mode: str = "auto"  # auto|cat|dedup
    concatenate_output: str = "step5_production_cat.xtc"
    no_pbc_output: str = "step5_production_noPBC.xtc"
    index_file: str = "new_index.ndx"
    protein_group_name: str = "Protein"
    ligand_group_name: str = "LIGAND"
    complex_group_name: str = "COMPLEX"
    pca_dir: str = "PCA"
    mmpbsa_input: str = "mmpbsa.in"
    mmpbsa_run_script: str = "run_mmpbsa.sh"
    mmpbsa_results_prefix: str = "FINAL_RESULTS_MMPBSA"
    mmpbsa_decomp_prefix: str = "FINAL_DECOMP_MMPBSA"
    pca_npcs: int = 10
    generate_vmd_script_name: str = "generate_md_metrics.tcl"
    metric_output_dir: str = "."
    run_vmd: bool = True
    run_mmpbsa: bool = False
    run_pca: bool = True
    pca_terminal_grouping: bool = True
    pca_rmsf_file: str = "RMSF_.dat"
    pca_reference_pdb: str = "step3_input.pdb"
    pca_reference_gro: str = "step3_input.gro"
    pca_index_file: str = "new_index_pca.ndx"
    pca_core_group_name: str = "core_no_terminals"
    pca_calpha_group_name: str = "core_no_terminals_Calpha"
    pca_terminal_smoothing_window: int = 3
    pca_terminal_mad_multiplier: float = 3.0
    pca_terminal_stable_run: int = 3
    pca_terminal_max_terminal_fraction: float = 0.25
    pca_core_residue_range: List[int] = field(default_factory=list)
    qc_enabled: bool = True
    strict_segment_sequence: bool = True
    use_settime: bool = False
    settime_starts_ps: List[float] = field(default_factory=list)


@dataclass
class WorkflowConfig:
    gmx: str = "gmx"
    vmd: str = "vmd"
    gmx_mmpbsa: str = "gmx_MMPBSA"
    mpi_launcher: str = "mpirun"
    mpi_ranks: int = 24
    systems: List[SystemConfig] = field(default_factory=list)


def _to_path(base: Path, raw: str) -> Path:
    path = Path(raw).expanduser()
    if path.is_absolute():
        return path
    return (base / path).resolve()


def _load_config(path: Path) -> WorkflowConfig:
    raw = yaml.safe_load(path.read_text()) or {}
    defaults = raw.get("defaults", {})
    systems_raw = raw.get("systems", [])

    cfg = WorkflowConfig(
        gmx=defaults.get("gmx", "gmx"),
        vmd=defaults.get("vmd", "vmd"),
        gmx_mmpbsa=defaults.get("gmx_mmpbsa", "gmx_MMPBSA"),
        mpi_launcher=defaults.get("mpi_launcher", "mpirun"),
        mpi_ranks=int(defaults.get("mpi_ranks", 24)),
    )

    root = path.parent.resolve()
    systems: List[SystemConfig] = []
    for item in systems_raw:
        workdir = _to_path(root, str(item["workdir"]))
        systems.append(
            SystemConfig(
                name=str(item["name"]),
                workdir=workdir,
                ligand_resname=str(item["ligand_resname"]),
                topology_for_vmd=str(item.get("topology_for_vmd", "step3_input.psf")),
                structure_gro=str(item.get("structure_gro", "step5_production.gro")),
                structure_tpr=str(item.get("structure_tpr", "step5_production.tpr")),
                topology_top=str(item.get("topology_top", "topol.top")),
                trajectory_patterns=list(item.get("trajectory_patterns", ["step5_*.xtc", "step5_production*.xtc", "prod*.xtc"])),
                trjcat_mode=str(item.get("trjcat_mode", "auto")).lower(),
                concatenate_output=str(item.get("concatenate_output", "step5_production_cat.xtc")),
                no_pbc_output=str(item.get("no_pbc_output", "step5_production_noPBC.xtc")),
                index_file=str(item.get("index_file", "new_index.ndx")),
                protein_group_name=str(item.get("protein_group_name", "Protein")),
                ligand_group_name=str(item.get("ligand_group_name", "LIGAND")),
                complex_group_name=str(item.get("complex_group_name", "COMPLEX")),
                pca_dir=str(item.get("pca_dir", "PCA")),
                mmpbsa_input=str(item.get("mmpbsa_input", "mmpbsa.in")),
                mmpbsa_run_script=str(item.get("mmpbsa_run_script", "run_mmpbsa.sh")),
                mmpbsa_results_prefix=str(item.get("mmpbsa_results_prefix", "FINAL_RESULTS_MMPBSA")),
                mmpbsa_decomp_prefix=str(item.get("mmpbsa_decomp_prefix", "FINAL_DECOMP_MMPBSA")),
                pca_npcs=int(item.get("pca_npcs", 10)),
                generate_vmd_script_name=str(item.get("generate_vmd_script_name", "generate_md_metrics.tcl")),
                metric_output_dir=str(item.get("metric_output_dir", ".")),
                run_vmd=bool(item.get("run_vmd", True)),
                run_mmpbsa=bool(item.get("run_mmpbsa", False)),
                run_pca=bool(item.get("run_pca", True)),
                pca_terminal_grouping=bool(item.get("pca_terminal_grouping", True)),
                pca_rmsf_file=str(item.get("pca_rmsf_file", "RMSF_.dat")),
                pca_reference_pdb=str(item.get("pca_reference_pdb", "step3_input.pdb")),
                pca_reference_gro=str(item.get("pca_reference_gro", "step3_input.gro")),
                pca_index_file=str(item.get("pca_index_file", "new_index_pca.ndx")),
                pca_core_group_name=str(item.get("pca_core_group_name", "core_no_terminals")),
                pca_calpha_group_name=str(item.get("pca_calpha_group_name", "core_no_terminals_Calpha")),
                pca_terminal_smoothing_window=int(item.get("pca_terminal_smoothing_window", 3)),
                pca_terminal_mad_multiplier=float(item.get("pca_terminal_mad_multiplier", 3.0)),
                pca_terminal_stable_run=int(item.get("pca_terminal_stable_run", 3)),
                pca_terminal_max_terminal_fraction=float(item.get("pca_terminal_max_terminal_fraction", 0.25)),
                pca_core_residue_range=[int(v) for v in item.get("pca_core_residue_range", [])],
                qc_enabled=bool(item.get("qc_enabled", True)),
                strict_segment_sequence=bool(item.get("strict_segment_sequence", True)),
                use_settime=bool(item.get("use_settime", False)),
                settime_starts_ps=[float(v) for v in item.get("settime_starts_ps", [])],
            )
        )
    cfg.systems = systems
    return cfg


def _segment_sort_key(name: str) -> Tuple[int, int, str]:
    lowered = name.lower()
    for pattern in (
        r"(?:^|[_\-])step(?:5)?[_\-]?(\d+)\.xtc$",
        r"(?:^|[_\-])seg(?:ment)?[_\-]?(\d+)\.xtc$",
        r"(?:^|[_\-])part[_\-]?(\d+)\.xtc$",
        r"(?:^|[_\-])prod(?:uction)?[_\-]?(\d+)\.xtc$",
        r"(\d+)\.xtc$",
    ):
        m = re.search(pattern, lowered)
        if m:
            return (0, int(m.group(1)), lowered)
    return (1, 0, lowered)


def _extract_segment_number(name: str) -> Optional[int]:
    lowered = name.lower()
    for pattern in (
        r"(?:^|[_\-])step(?:5)?[_\-]?(\d+)\.xtc$",
        r"(?:^|[_\-])seg(?:ment)?[_\-]?(\d+)\.xtc$",
        r"(?:^|[_\-])part[_\-]?(\d+)\.xtc$",
        r"(?:^|[_\-])prod(?:uction)?[_\-]?(\d+)\.xtc$",
    ):
        match = re.search(pattern, lowered)
        if match:
            return int(match.group(1))
    return None


def _collect_trajectory_parts(system: SystemConfig) -> List[Path]:
    found: List[Path] = []
    for pattern in system.trajectory_patterns:
        found.extend(system.workdir.glob(pattern))

    unique: Dict[Path, None] = {}
    for path in found:
        if not path.is_file():
            continue
        name = path.name.lower()
        if "nopbc" in name or "cat" in name or name.startswith("fit_"):
            continue
        unique[path.resolve()] = None

    ordered = sorted(unique.keys(), key=lambda p: _segment_sort_key(p.name))
    return ordered


def _build_parts_qc(system: SystemConfig, parts: List[Path]) -> Dict[str, object]:
    numbers: List[int] = []
    numbered_files = 0
    for path in parts:
        n = _extract_segment_number(path.name)
        if n is not None:
            numbers.append(n)
            numbered_files += 1

    missing_numbers: List[int] = []
    if numbers:
        n_min = min(numbers)
        n_max = max(numbers)
        observed = set(numbers)
        missing_numbers = [n for n in range(n_min, n_max + 1) if n not in observed]

    report = {
        "parts_count": len(parts),
        "is_split_input": len(parts) > 1,
        "numbered_parts_count": numbered_files,
        "segment_numbers": numbers,
        "missing_segment_numbers": missing_numbers,
        "sequence_ok": len(missing_numbers) == 0,
        "parts": [
            {
                "path": str(path),
                "size_bytes": path.stat().st_size,
            }
            for path in parts
        ],
    }

    if system.strict_segment_sequence and missing_numbers:
        missing_text = ", ".join(str(n) for n in missing_numbers[:20])
        raise ValueError(
            f"Detected missing trajectory segment numbers for {system.name}: {missing_text}. "
            "Refusing to continue because strict_segment_sequence=true."
        )

    return report


def _parse_ndx_groups(path: Path) -> Dict[str, int]:
    groups: Dict[str, int] = {}
    idx = 0
    for line in path.read_text().splitlines():
        line = line.strip()
        if line.startswith("[") and line.endswith("]"):
            name = line[1:-1].strip()
            groups[name] = idx
            idx += 1
    return groups


def _run_command(
    cmd: Sequence[str],
    *,
    cwd: Path,
    stdin: Optional[str],
    dry_run: bool,
    log_file: Path,
) -> None:
    rendered = " ".join(shlex.quote(part) for part in cmd)
    log_file.parent.mkdir(parents=True, exist_ok=True)
    with log_file.open("a", encoding="utf-8") as handle:
        handle.write(f"$ {rendered}\n")
        if stdin:
            handle.write(f"[stdin]\n{stdin}\n")
        handle.write("\n")

    if dry_run:
        logger.info(f"[dry-run] {rendered}")
        return

    proc = subprocess.run(
        list(cmd),
        input=stdin,
        text=True,
        cwd=str(cwd),
        capture_output=True,
        check=False,
    )

    with log_file.open("a", encoding="utf-8") as handle:
        if proc.stdout:
            handle.write("[stdout]\n")
            handle.write(proc.stdout)
            handle.write("\n")
        if proc.stderr:
            handle.write("[stderr]\n")
            handle.write(proc.stderr)
            handle.write("\n")

    if proc.returncode != 0:
        raise RuntimeError(f"Command failed ({proc.returncode}): {rendered}")


def _build_trjcat_command(
    cfg: WorkflowConfig,
    system: SystemConfig,
    parts: List[Path],
    mode: str,
    cat_out: Path,
    dry_run: bool,
) -> Tuple[List[str], Optional[str]]:
    """
    Build trjcat command/stdin with explicit merge policy.

    Context7/GROMACS guidance:
    - gmx trjcat concatenates in sorted order.
    - default behavior resolves duplicate timestamps by preferring later files.
    - -cat keeps identical timestamps (literal paste/append semantics).
    - -settime allows explicit start times per part.
    """
    cmd = [cfg.gmx, "trjcat", "-f", *[str(path) for path in parts], "-o", str(cat_out)]
    stdin = None
    if mode == "cat":
        cmd.append("-cat")

    if system.use_settime:
        cmd.append("-settime")
        if system.settime_starts_ps:
            if len(system.settime_starts_ps) != len(parts):
                raise ValueError(
                    f"use_settime=true but settime_starts_ps count ({len(system.settime_starts_ps)}) "
                    f"does not match number of trajectory parts ({len(parts)})."
                )
            stdin = "\n".join(str(v) for v in system.settime_starts_ps) + "\n"
        elif not dry_run:
            raise ValueError(
                "use_settime=true requires settime_starts_ps for non-dry-run execution."
            )
    return cmd, stdin


def _run_command_capture(
    cmd: Sequence[str],
    *,
    cwd: Path,
    stdin: Optional[str],
    dry_run: bool,
    log_file: Path,
) -> Dict[str, object]:
    rendered = " ".join(shlex.quote(part) for part in cmd)
    log_file.parent.mkdir(parents=True, exist_ok=True)
    with log_file.open("a", encoding="utf-8") as handle:
        handle.write(f"$ {rendered}\n")
        if stdin:
            handle.write(f"[stdin]\n{stdin}\n")
        handle.write("\n")

    if dry_run:
        logger.info(f"[dry-run] {rendered}")
        return {"returncode": 0, "stdout": "", "stderr": "", "rendered": rendered}

    proc = subprocess.run(
        list(cmd),
        input=stdin,
        text=True,
        cwd=str(cwd),
        capture_output=True,
        check=False,
    )
    with log_file.open("a", encoding="utf-8") as handle:
        if proc.stdout:
            handle.write("[stdout]\n")
            handle.write(proc.stdout)
            handle.write("\n")
        if proc.stderr:
            handle.write("[stderr]\n")
            handle.write(proc.stderr)
            handle.write("\n")

    return {
        "returncode": proc.returncode,
        "stdout": proc.stdout or "",
        "stderr": proc.stderr or "",
        "rendered": rendered,
    }


def _run_gmx_check_qc(
    cfg: WorkflowConfig,
    system: SystemConfig,
    trajectory: Path,
    log_file: Path,
    dry_run: bool,
) -> Dict[str, object]:
    result = _run_command_capture(
        [cfg.gmx, "check", "-f", str(trajectory)],
        cwd=system.workdir,
        stdin=None,
        dry_run=dry_run,
        log_file=log_file,
    )
    if dry_run:
        return {
            "checked": False,
            "skipped": True,
            "reason": "dry_run",
            "trajectory": str(trajectory),
        }

    text = f"{result['stdout']}\n{result['stderr']}"
    mismatch_lines = re.findall(r"timesteps?.*don't match", text, flags=re.IGNORECASE)
    last_frame_match = re.search(
        r"Last frame\s+(\d+)\s+time\s+([-+0-9.eE]+)",
        text,
        flags=re.IGNORECASE,
    )
    time_summary_match = re.search(
        r"^\s*Time\s+(\d+)\s+([-+0-9.eE]+)",
        text,
        flags=re.IGNORECASE | re.MULTILINE,
    )

    last_frame = int(last_frame_match.group(1)) if last_frame_match else None
    last_time_ps = float(last_frame_match.group(2)) if last_frame_match else None
    time_frames = int(time_summary_match.group(1)) if time_summary_match else None
    timestep_ps = float(time_summary_match.group(2)) if time_summary_match else None

    return {
        "checked": True,
        "trajectory": str(trajectory),
        "gmx_check_returncode": result["returncode"],
        "time_mismatch_count": len(mismatch_lines),
        "last_frame": last_frame,
        "last_time_ps": last_time_ps,
        "time_frames": time_frames,
        "timestep_ps": timestep_ps,
        "valid": result["returncode"] == 0 and len(mismatch_lines) == 0,
    }


def _run_toolkit_qc(
    system: SystemConfig,
    no_pbc: Path,
    ndx: Path,
    dry_run: bool,
) -> Dict[str, object]:
    if dry_run or not system.qc_enabled:
        return {
            "enabled": system.qc_enabled,
            "ran": False,
            "skipped": True,
            "reason": "dry_run" if dry_run else "qc_enabled=false",
        }

    try:
        from ..qc import QCAnalyzer, QCConfig  # noqa: WPS433
    except Exception as exc:  # noqa: BLE001
        return {
            "enabled": system.qc_enabled,
            "ran": False,
            "skipped": True,
            "reason": f"qc_module_unavailable: {exc}",
        }

    qc_dir = system.workdir / "_orchestrator" / "qc"
    cfg = QCConfig(
        base_dir=system.workdir,
        output_dir=qc_dir,
        topology=system.workdir / system.structure_gro,
        trajectories=[no_pbc],
        index_file=ndx,
        expected_groups=[
            system.protein_group_name,
            system.complex_group_name,
        ],
        protein_selection="protein",
        ligand_selection=f"resname {system.ligand_resname}",
        expected_replicates=1,
        fail_on_error=False,
    )
    analyzer = QCAnalyzer(cfg)
    qc_result = analyzer.run_analysis()
    return {
        "enabled": system.qc_enabled,
        "ran": True,
        "result": qc_result,
        "report_file": qc_result.get("report_file"),
        "success": qc_result.get("success", False),
    }


def _resolve_mode(mode: str, parts: List[Path]) -> str:
    if mode in {"cat", "dedup"}:
        return mode
    # auto mode: if every segment looks like a restart part, use cat.
    numeric_like = 0
    for path in parts:
        if _segment_sort_key(path.name)[0] == 0:
            numeric_like += 1
    if len(parts) > 1 and numeric_like >= max(1, len(parts) - 1):
        return "cat"
    return "dedup"


def _build_index(
    cfg: WorkflowConfig,
    system: SystemConfig,
    log_file: Path,
    dry_run: bool,
) -> Dict[str, int]:
    gro = system.workdir / system.structure_gro
    ndx = system.workdir / system.index_file

    _run_command(
        [cfg.gmx, "make_ndx", "-f", str(gro), "-o", str(ndx)],
        cwd=system.workdir,
        stdin="q\n",
        dry_run=dry_run,
        log_file=log_file,
    )

    if dry_run:
        return {}

    groups = _parse_ndx_groups(ndx)
    if system.protein_group_name not in groups:
        raise ValueError(f"Protein group '{system.protein_group_name}' not found in {ndx}")

    ligand_candidates = [
        system.ligand_group_name,
        system.ligand_resname,
        system.ligand_resname.upper(),
        system.ligand_resname.lower(),
    ]
    ligand_name = next((name for name in ligand_candidates if name in groups), None)
    if ligand_name is None:
        raise ValueError(
            f"Ligand group not found in {ndx}. Tried: {ligand_candidates}. "
            "Set ligand_group_name to an existing group name."
        )

    protein_id = groups[system.protein_group_name]
    ligand_id = groups[ligand_name]
    group_count = len(groups)

    stdin = f"{protein_id} | {ligand_id}\nname {group_count} {system.complex_group_name}\nq\n"
    _run_command(
        [cfg.gmx, "make_ndx", "-f", str(gro), "-n", str(ndx), "-o", str(ndx)],
        cwd=system.workdir,
        stdin=stdin,
        dry_run=dry_run,
        log_file=log_file,
    )

    groups = _parse_ndx_groups(ndx)
    if system.complex_group_name not in groups:
        raise ValueError(f"Complex group '{system.complex_group_name}' not found in {ndx} after make_ndx.")

    return groups


def _prepare_pca_terminal_index(
    cfg: WorkflowConfig,
    system: SystemConfig,
    log_file: Path,
    dry_run: bool,
) -> Dict[str, object]:
    """Create RMSF-guided PCA index groups that trim terminal overhangs."""
    if not system.pca_terminal_grouping:
        return {
            "enabled": False,
            "used": False,
            "index_file": str(system.workdir / system.index_file),
            "calpha_group_name": system.protein_group_name,
        }

    try:
        from ..pca.config import PCATerminalDetectionConfig  # noqa: WPS433
        from ..pca.prep import (  # noqa: WPS433
            build_index_plan,
            build_residue_map,
            count_index_groups,
            detect_terminals,
            parse_gro_residues,
            parse_pdb_residues,
            parse_rmsf_file,
            write_index_plan,
            write_residue_map,
            write_terminal_detection,
        )
    except Exception as exc:  # noqa: BLE001
        return {
            "enabled": True,
            "used": False,
            "skipped_reason": f"pca_terminal_module_unavailable: {exc}",
            "index_file": str(system.workdir / system.index_file),
            "calpha_group_name": system.protein_group_name,
        }

    rmsf_path = system.workdir / system.pca_rmsf_file
    gro_path = system.workdir / system.pca_reference_gro
    pdb_path = system.workdir / system.pca_reference_pdb
    for required in (rmsf_path, gro_path):
        if not required.exists():
            raise FileNotFoundError(
                f"PCA terminal grouping needs file not found: {required}"
            )

    core_range = None
    if system.pca_core_residue_range:
        if len(system.pca_core_residue_range) != 2:
            raise ValueError("pca_core_residue_range must have exactly two integers [start, end].")
        core_range = (
            int(system.pca_core_residue_range[0]),
            int(system.pca_core_residue_range[1]),
        )

    terminal_cfg = PCATerminalDetectionConfig(
        enabled=True,
        rmsf_file=str(rmsf_path),
        pdb_file=str(pdb_path),
        gro_file=str(gro_path),
        smoothing_window=system.pca_terminal_smoothing_window,
        mad_multiplier=system.pca_terminal_mad_multiplier,
        stable_run=system.pca_terminal_stable_run,
        max_terminal_fraction=system.pca_terminal_max_terminal_fraction,
        core_residue_range=core_range,
    )

    rmsf_values = parse_rmsf_file(rmsf_path)
    gro_residues = parse_gro_residues(gro_path)
    pdb_residues = parse_pdb_residues(pdb_path) if pdb_path.exists() else None
    residue_map = build_residue_map(rmsf_values, gro_residues, pdb_residues)
    detection = detect_terminals(residue_map, terminal_cfg)

    out_dir = system.workdir / "_orchestrator" / "pca_terminal_index"
    out_dir.mkdir(parents=True, exist_ok=True)
    write_residue_map(residue_map, out_dir / "residue_map.csv")
    write_terminal_detection(detection, out_dir / "terminal_detection.json")

    if dry_run:
        return {
            "enabled": True,
            "used": True,
            "dry_run": True,
            "index_file": str(system.workdir / system.pca_index_file),
            "calpha_group_name": system.pca_calpha_group_name,
            "core_range_gro": [detection.gro_start_resid, detection.gro_end_resid],
            "core_range_native": [detection.native_start_resid, detection.native_end_resid],
        }

    default_index = out_dir / "_default_index.ndx"
    final_index = system.workdir / system.pca_index_file

    _run_command(
        [cfg.gmx, "make_ndx", "-f", str(gro_path), "-o", str(default_index)],
        cwd=system.workdir,
        stdin="q\n",
        dry_run=dry_run,
        log_file=log_file,
    )
    group_count = count_index_groups(default_index)
    index_plan = build_index_plan(
        detection,
        existing_group_count=group_count,
        core_group_name=system.pca_core_group_name,
        calpha_group_name=system.pca_calpha_group_name,
    )
    write_index_plan(index_plan, out_dir / "pca_index_plan.txt")

    _run_command(
        [
            cfg.gmx,
            "make_ndx",
            "-f",
            str(gro_path),
            "-n",
            str(default_index),
            "-o",
            str(final_index),
        ],
        cwd=system.workdir,
        stdin=index_plan.stdin,
        dry_run=dry_run,
        log_file=log_file,
    )
    if default_index.exists():
        default_index.unlink()

    groups = _parse_ndx_groups(final_index)
    if system.pca_calpha_group_name not in groups:
        raise ValueError(
            f"PCA C-alpha group '{system.pca_calpha_group_name}' not found in {final_index}"
        )

    return {
        "enabled": True,
        "used": True,
        "index_file": str(final_index),
        "calpha_group_name": system.pca_calpha_group_name,
        "core_group_name": system.pca_core_group_name,
        "core_range_gro": [detection.gro_start_resid, detection.gro_end_resid],
        "core_range_native": [detection.native_start_resid, detection.native_end_resid],
        "residue_count": len(residue_map),
    }


def _write_mmpbsa_input(system: SystemConfig) -> Path:
    path = system.workdir / system.mmpbsa_input
    if path.exists():
        return path
    path.write_text(DEFAULT_MMPBSA_IN.format(sys_name=system.name))
    return path


def _write_mmpbsa_run_script(
    cfg: WorkflowConfig,
    system: SystemConfig,
    group_ids: Dict[str, int],
) -> Path:
    script_path = system.workdir / system.mmpbsa_run_script
    mmpbsa_input = system.workdir / system.mmpbsa_input
    tpr = system.workdir / system.structure_tpr
    top = system.workdir / system.topology_top
    ndx = system.workdir / system.index_file
    traj = system.workdir / system.no_pbc_output

    protein_id = group_ids[system.protein_group_name]
    ligand_id = group_ids.get(system.ligand_group_name, group_ids.get(system.ligand_resname))
    if ligand_id is None:
        # fallback: find by case-insensitive name
        for name, gid in group_ids.items():
            if name.lower() in {system.ligand_group_name.lower(), system.ligand_resname.lower()}:
                ligand_id = gid
                break
    if ligand_id is None:
        raise ValueError("Unable to resolve ligand group id for mmpbsa run script.")

    script = f"""#!/usr/bin/env bash
set -euo pipefail

{cfg.mpi_launcher} -np {cfg.mpi_ranks} {cfg.gmx_mmpbsa} MPI -O \\
  -i "{mmpbsa_input}" \\
  -cs "{tpr}" \\
  -cp "{top}" \\
  -ci "{ndx}" \\
  -cg {protein_id} {ligand_id} \\
  -ct "{traj}" \\
  -o "{system.mmpbsa_results_prefix}.dat" \\
  -eo "{system.mmpbsa_results_prefix}.csv" \\
  -do "{system.mmpbsa_decomp_prefix}.dat" \\
  -deo "{system.mmpbsa_decomp_prefix}.csv"
"""
    script_path.write_text(script)
    script_path.chmod(0o755)
    return script_path


def _prepare_vmd_script(system: SystemConfig) -> Path:
    output_dir = system.workdir / "_orchestrator"
    task = {
        "outputs": ["md_vmd"],
        "md_vmd_name": system.generate_vmd_script_name,
        "topology": system.topology_for_vmd,
        "trajectory": system.no_pbc_output,
        "ligand_selection": f"resname {system.ligand_resname}",
        "protein_selection": "protein",
        "metric_output_dir": system.metric_output_dir,
    }
    result = generate_upstream_scripts(task, output_dir)
    return Path(result["scripts"][0])


def _validate_mmpbsa_inputs(system: SystemConfig, group_ids: Dict[str, int]) -> Dict[str, object]:
    required_files = [
        system.workdir / system.mmpbsa_input,
        system.workdir / system.structure_tpr,
        system.workdir / system.topology_top,
        system.workdir / system.index_file,
        system.workdir / system.no_pbc_output,
    ]
    missing = [str(path) for path in required_files if not path.exists()]
    nonempty = [str(path) for path in required_files if path.exists() and path.stat().st_size > 0]

    ligand_ok = False
    for name in group_ids:
        if name.lower() in {system.ligand_group_name.lower(), system.ligand_resname.lower()}:
            ligand_ok = True
            break

    valid = (
        len(missing) == 0
        and system.protein_group_name in group_ids
        and ligand_ok
    )
    report = {
        "valid": valid,
        "missing_files": missing,
        "nonempty_files": nonempty,
        "group_ids": group_ids,
        "protein_group_name": system.protein_group_name,
        "ligand_group_name": system.ligand_group_name,
        "ligand_resname": system.ligand_resname,
    }
    out = system.workdir / "_orchestrator" / "mmpbsa_validation.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(report, indent=2))
    return report


def _run_single_system(
    cfg: WorkflowConfig,
    system: SystemConfig,
    dry_run: bool,
) -> Dict[str, object]:
    if not system.workdir.exists():
        raise FileNotFoundError(f"System workdir does not exist: {system.workdir}")

    required = [system.structure_gro, system.structure_tpr, system.topology_top, system.topology_for_vmd]
    for rel in required:
        path = system.workdir / rel
        if not path.exists():
            raise FileNotFoundError(f"Missing required file: {path}")

    log_file = system.workdir / "_orchestrator" / "workflow_commands.log"
    log_file.parent.mkdir(parents=True, exist_ok=True)
    if log_file.exists():
        log_file.unlink()

    parts = _collect_trajectory_parts(system)
    if not parts:
        raise FileNotFoundError(
            f"No trajectory parts matched patterns {system.trajectory_patterns} in {system.workdir}"
        )
    parts_qc = _build_parts_qc(system, parts)

    mode = _resolve_mode(system.trjcat_mode, parts)
    cat_out = system.workdir / system.concatenate_output
    trjcat_cmd, trjcat_stdin = _build_trjcat_command(
        cfg=cfg,
        system=system,
        parts=parts,
        mode=mode,
        cat_out=cat_out,
        dry_run=dry_run,
    )
    _run_command(
        trjcat_cmd,
        cwd=system.workdir,
        stdin=trjcat_stdin,
        dry_run=dry_run,
        log_file=log_file,
    )
    concat_qc = _run_gmx_check_qc(cfg, system, cat_out, log_file, dry_run)
    if not dry_run and not concat_qc.get("valid", False):
        raise RuntimeError(
            f"Concatenated trajectory failed QC for {system.name}: "
            f"time_mismatch_count={concat_qc.get('time_mismatch_count')}, "
            f"returncode={concat_qc.get('gmx_check_returncode')}"
        )

    group_ids = _build_index(cfg, system, log_file, dry_run)

    no_pbc = system.workdir / system.no_pbc_output
    ndx = system.workdir / system.index_file
    tpr = system.workdir / system.structure_tpr
    _run_command(
        [
            cfg.gmx,
            "trjconv",
            "-f",
            str(cat_out),
            "-o",
            str(no_pbc),
            "-s",
            str(tpr),
            "-pbc",
            "mol",
            "-center",
            "-n",
            str(ndx),
            "-ur",
            "compact",
        ],
        cwd=system.workdir,
        stdin=f"{system.complex_group_name}\nSystem\n",
        dry_run=dry_run,
        log_file=log_file,
    )
    no_pbc_qc = _run_gmx_check_qc(cfg, system, no_pbc, log_file, dry_run)
    if not dry_run and not no_pbc_qc.get("valid", False):
        raise RuntimeError(
            f"NoPBC trajectory failed QC for {system.name}: "
            f"time_mismatch_count={no_pbc_qc.get('time_mismatch_count')}, "
            f"returncode={no_pbc_qc.get('gmx_check_returncode')}"
        )
    toolkit_qc = _run_toolkit_qc(system, no_pbc, ndx, dry_run)

    if system.run_vmd:
        vmd_script = _prepare_vmd_script(system)
        _run_command(
            [cfg.vmd, "-dispdev", "text", "-e", str(vmd_script)],
            cwd=system.workdir,
            stdin=None,
            dry_run=dry_run,
            log_file=log_file,
        )
    else:
        vmd_script = system.workdir / "_orchestrator" / system.generate_vmd_script_name
        _prepare_vmd_script(system)

    mmpbsa_in = _write_mmpbsa_input(system)
    if dry_run:
        mmpbsa_script = system.workdir / system.mmpbsa_run_script
        validation = {"valid": True, "missing_files": [], "group_ids": group_ids}
    else:
        mmpbsa_script = _write_mmpbsa_run_script(cfg, system, group_ids)
        validation = _validate_mmpbsa_inputs(system, group_ids)

    if system.run_mmpbsa:
        _run_command(
            [str(mmpbsa_script)],
            cwd=system.workdir,
            stdin=None,
            dry_run=dry_run,
            log_file=log_file,
        )

    pca_outputs: Dict[str, str] = {}
    pca_terminal_index = {
        "enabled": system.pca_terminal_grouping,
        "used": False,
    }
    if system.run_pca:
        pca_dir = (system.workdir / system.pca_dir).resolve()
        pca_dir.mkdir(parents=True, exist_ok=True)
        calpha = pca_dir / "step5_production_noPBC_Calpha.xtc"
        ref = pca_dir / "ref.pdb"
        pca_terminal_index = _prepare_pca_terminal_index(
            cfg=cfg,
            system=system,
            log_file=log_file,
            dry_run=dry_run,
        )
        pca_index = Path(str(pca_terminal_index["index_file"]))
        pca_group_name = str(pca_terminal_index["calpha_group_name"])

        _run_command(
            [cfg.gmx, "trjconv", "-f", str(no_pbc), "-o", str(calpha), "-s", str(tpr), "-n", str(pca_index)],
            cwd=system.workdir,
            stdin=f"{pca_group_name}\n",
            dry_run=dry_run,
            log_file=log_file,
        )
        _run_command(
            [cfg.gmx, "trjconv", "-s", str(tpr), "-f", str(no_pbc), "-dump", "0", "-o", str(ref), "-n", str(pca_index)],
            cwd=system.workdir,
            stdin=f"{pca_group_name}\n",
            dry_run=dry_run,
            log_file=log_file,
        )
        _run_command(
            [
                cfg.gmx,
                "covar",
                "-mwa",
                "-ref",
                "-s",
                str(ref),
                "-f",
                str(calpha),
                "-v",
                str(pca_dir / "eigenvectors_all_ref.trr"),
                "-o",
                str(pca_dir / "eigenvals_all_ref.xvg"),
            ],
            cwd=system.workdir,
            stdin="System\nSystem\n",
            dry_run=dry_run,
            log_file=log_file,
        )
        _run_command(
            [
                cfg.gmx,
                "anaeig",
                "-proj",
                str(pca_dir / "proj.xvg"),
                "-first",
                "1",
                "-last",
                str(system.pca_npcs),
                "-s",
                str(ref),
                "-f",
                str(calpha),
                "-v",
                str(pca_dir / "eigenvectors_all_ref.trr"),
                "-eig",
                str(pca_dir / "eigenvals_all_ref.xvg"),
            ],
            cwd=system.workdir,
            stdin="System\nSystem\n",
            dry_run=dry_run,
            log_file=log_file,
        )
        _run_command(
            [
                cfg.gmx,
                "analyze",
                "-n",
                str(system.pca_npcs),
                "-cc",
                str(pca_dir / "cc_all.xvg"),
                "-f",
                str(pca_dir / "proj.xvg"),
            ],
            cwd=system.workdir,
            stdin=None,
            dry_run=dry_run,
            log_file=log_file,
        )
        for first, last in (("1", "2"), ("1", "3"), ("2", "3")):
            _run_command(
                [
                    cfg.gmx,
                    "anaeig",
                    "-s",
                    str(ref),
                    "-f",
                    str(calpha),
                    "-2d",
                    str(pca_dir / f"2dproj_{first}{last}.xvg"),
                    "-first",
                    first,
                    "-last",
                    last,
                    "-v",
                    str(pca_dir / "eigenvectors_all_ref.trr"),
                    "-eig",
                    str(pca_dir / "eigenvals_all_ref.xvg"),
                ],
                cwd=system.workdir,
                stdin="System\nSystem\n",
                dry_run=dry_run,
                log_file=log_file,
            )
        pca_outputs = {
            "pca_dir": str(pca_dir),
            "pca_index_file": str(pca_index),
            "pca_group_name": pca_group_name,
            "eigenvals": str(pca_dir / "eigenvals_all_ref.xvg"),
            "projection": str(pca_dir / "proj.xvg"),
            "cosine_content": str(pca_dir / "cc_all.xvg"),
        }

    report = {
        "system": system.name,
        "workdir": str(system.workdir),
        "trajectory_parts": [str(path) for path in parts],
        "trjcat_mode_used": mode,
        "trajectory_qc": {
            "input_parts_qc": parts_qc,
            "concatenated_qc": concat_qc,
            "no_pbc_qc": no_pbc_qc,
            "toolkit_qc": toolkit_qc,
        },
        "pca_terminal_index": pca_terminal_index,
        "merge_policy": {
            "trjcat_mode_requested": system.trjcat_mode,
            "trjcat_mode_used": mode,
            "use_settime": system.use_settime,
            "settime_starts_ps": system.settime_starts_ps,
            "command": " ".join(shlex.quote(part) for part in trjcat_cmd),
        },
        "outputs": {
            "concatenated_xtc": str(cat_out),
            "no_pbc_xtc": str(no_pbc),
            "index_file": str(system.workdir / system.index_file),
            "vmd_script": str(vmd_script),
            "mmpbsa_input": str(mmpbsa_in),
            "mmpbsa_run_script": str(mmpbsa_script),
            **pca_outputs,
        },
        "mmpbsa_validation": validation,
        "dry_run": dry_run,
    }

    report_path = system.workdir / "_orchestrator" / "workflow_report.json"
    report_path.write_text(json.dumps(report, indent=2))
    return report


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Run orchestrated upstream workflow: index -> noPBC -> VMD -> MMPBSA prepare/validate -> PCA",
    )
    parser.add_argument("--config", "-c", type=Path, required=True, help="YAML workflow config")
    parser.add_argument("--dry-run", action="store_true", help="Print commands and write plan without execution")
    args = parser.parse_args()

    config = _load_config(args.config.resolve())
    if not config.systems:
        raise SystemExit("No systems defined in config.")

    all_reports: List[Dict[str, object]] = []
    failed = False
    for system in config.systems:
        logger.info(f"=== Running orchestrated workflow: {system.name} ===")
        try:
            report = _run_single_system(config, system, args.dry_run)
            all_reports.append(report)
            logger.info(f"Completed: {system.name}")
        except Exception as exc:  # noqa: BLE001
            failed = True
            logger.error(f"Failed: {system.name} -> {exc}")
            all_reports.append(
                {
                    "system": system.name,
                    "workdir": str(system.workdir),
                    "error": str(exc),
                    "dry_run": args.dry_run,
                }
            )

    summary = {
        "config": str(args.config.resolve()),
        "dry_run": args.dry_run,
        "systems_total": len(config.systems),
        "systems_failed": sum(1 for item in all_reports if "error" in item),
        "reports": all_reports,
    }
    summary_path = args.config.resolve().with_suffix(".orchestrator_summary.json")
    summary_path.write_text(json.dumps(summary, indent=2))
    logger.info(f"Summary written: {summary_path}")

    if failed:
        sys.exit(1)


if __name__ == "__main__":
    main()
