"""Generate upstream GROMACS/VMD helper scripts without executing them."""

from __future__ import annotations

from pathlib import Path
from typing import Dict, Iterable, List


def _enabled_outputs(task: Dict) -> List[str]:
    outputs = task.get("outputs") or ["md_vmd", "mmpbsa", "pca"]
    return [str(item).lower() for item in outputs]


def generate_upstream_scripts(task: Dict, output_dir: Path) -> Dict:
    """Write dry-run helper scripts for upstream trajectory processing."""
    output_dir.mkdir(parents=True, exist_ok=True)
    written: List[str] = []
    outputs = _enabled_outputs(task)

    if "md_vmd" in outputs:
        path = output_dir / task.get("md_vmd_name", "generate_md_metrics.tcl")
        path.write_text(_build_md_vmd_script(task))
        written.append(str(path))

    if "mmpbsa" in outputs:
        path = output_dir / task.get("mmpbsa_name", "run_mmpbsa.sh")
        path.write_text(_build_mmpbsa_script(task))
        path.chmod(0o755)
        written.append(str(path))

    if "pca" in outputs:
        path = output_dir / task.get("pca_name", "prepare_pca.sh")
        path.write_text(_build_pca_script(task))
        path.chmod(0o755)
        written.append(str(path))

    return {"success": True, "scripts": written}


def _build_md_vmd_script(task: Dict) -> str:
    topology = task.get("topology", "step3_input.psf")
    trajectory = task.get("trajectory", "step5_production_noPBC.xtc")
    ligand_selection = task.get("ligand_selection", "resname UNK")
    protein_selection = task.get("protein_selection", "protein")
    metric_output_dir = task.get("metric_output_dir", ".")
    max_frames = max(0, int(task.get("max_frames", 0)))

    template = r"""# VMD/TCL helper generated by gromacs-analysis-toolkit.
# Run manually from a system/replicate directory with:
#   vmd -dispdev text -e generate_md_metrics.tcl
#
# Output files are written to metric_output_dir and match the MD parser defaults:
#   RMSD_apo_.dat, RMSD_complex_.dat, RMSD_.dat, RMSF_.dat,
#   rog_.dat, SASA_.dat, hbonds_.dat, comcom_.dat

set topology "__TOPOLOGY__"
set trajectory "__TRAJECTORY__"
set protein_selection "__PROTEIN_SELECTION__"
set ligand_selection "__LIGAND_SELECTION__"
set metric_output_dir "__METRIC_OUTPUT_DIR__"
set max_frames __MAX_FRAMES__

proc outpath {filename} {
    global metric_output_dir
    file mkdir $metric_output_dir
    return [file join $metric_output_dir $filename]
}

proc selection_count {sel_text} {
    if {[catch {set sel [atomselect top $sel_text frame 0]} err]} {
        puts "WARNING: invalid selection '$sel_text': $err"
        return 0
    }
    set count [$sel num]
    $sel delete
    return $count
}

proc center_of_mass {selection} {
    if {[$selection num] <= 0} {
        error "center_of_mass: needs a selection with atoms"
    }
    set com [veczero]
    set mass 0
    foreach coord [$selection get {x y z}] m [$selection get mass] {
        set mass [expr {$mass + $m}]
        set com [vecadd $com [vecscale $m $coord]]
    }
    if {$mass == 0} {
        error "center_of_mass: total mass is zero"
    }
    return [vecscale [expr {1.0 / $mass}] $com]
}

proc gyr_radius {sel} {
    if {[$sel num] <= 0} {
        error "gyr_radius: must have at least one atom in selection"
    }
    set com [center_of_mass $sel]
    set sum 0
    foreach coord [$sel get {x y z}] {
        set sum [expr {$sum + [veclength2 [vecsub $coord $com]]}]
    }
    return [expr {sqrt($sum / ([$sel num] + 0.0))}]
}

proc pmodulo {n m} {
    if {$m == 0} {
        return $n
    }
    return [expr {$n - $m * floor(1.0 * $n / $m)}]
}

proc load_system {} {
    global topology trajectory max_frames nf
    if {![file exists $topology]} {
        puts "ERROR: topology not found: $topology"
        exit 1
    }
    if {![file exists $trajectory]} {
        puts "ERROR: trajectory not found: $trajectory"
        exit 1
    }
    puts "Loading topology: $topology"
    mol new $topology waitfor all
    puts "Loading trajectory: $trajectory"
    if {$max_frames > 0} {
        mol addfile $trajectory first 0 last [expr {$max_frames - 1}] waitfor all
    } else {
        mol addfile $trajectory waitfor all
    }
    set nf [molinfo top get numframes]
    puts "Loaded $nf frames"
}

proc align_to_protein_backbone {} {
    global protein_selection nf
    set backbone_selection "${protein_selection} and backbone"
    if {[selection_count $backbone_selection] <= 0} {
        puts "WARNING: no protein backbone atoms found; skipping alignment"
        return
    }
    puts "Aligning trajectory on: $backbone_selection"
    set reference [atomselect top $backbone_selection frame 0]
    set mobile [atomselect top $backbone_selection]
    set all_atoms [atomselect top all]
    for {set frame 0} {$frame < $nf} {incr frame} {
        $mobile frame $frame
        $all_atoms frame $frame
        set trans_mat [measure fit $mobile $reference]
        $all_atoms move $trans_mat
        if {$frame % 100 == 0} {
            puts "  aligned frame $frame / $nf"
        }
    }
    $reference delete
    $mobile delete
    $all_atoms delete
}

proc calc_rmsd {sel_text outfile_name} {
    global nf
    if {[selection_count $sel_text] <= 0} {
        puts "WARNING: skipping $outfile_name because selection is empty: $sel_text"
        return
    }
    puts "Calculating RMSD for: $sel_text"
    set reference [atomselect top $sel_text frame 0]
    set mobile [atomselect top $sel_text]
    set outfile [open [outpath $outfile_name] w]
    for {set frame 0} {$frame < $nf} {incr frame} {
        $mobile frame $frame
        puts $outfile [measure rmsd $mobile $reference]
    }
    close $outfile
    $reference delete
    $mobile delete
}

proc calc_rmsf {} {
    global protein_selection
    set sel_text "${protein_selection} and name CA"
    if {[selection_count $sel_text] <= 0} {
        puts "WARNING: skipping RMSF because selection is empty: $sel_text"
        return
    }
    puts "Calculating RMSF for: $sel_text"
    set sel [atomselect top $sel_text]
    set rmsf [measure rmsf $sel]
    set outfile [open [outpath "RMSF_.dat"] w]
    for {set i 0} {$i < [$sel num]} {incr i} {
        set resid [lindex [$sel get resid] $i]
        puts $outfile "$resid [lindex $rmsf $i]"
    }
    close $outfile
    $sel delete
}

proc calc_rog {} {
    global protein_selection nf
    if {[selection_count $protein_selection] <= 0} {
        puts "WARNING: skipping RoG because selection is empty: $protein_selection"
        return
    }
    puts "Calculating radius of gyration"
    set sel [atomselect top $protein_selection]
    set outfile [open [outpath "rog_.dat"] w]
    for {set frame 0} {$frame < $nf} {incr frame} {
        $sel frame $frame
        $sel update
        puts $outfile [gyr_radius $sel]
    }
    close $outfile
    $sel delete
}

proc calc_sasa {} {
    global protein_selection nf
    if {[selection_count $protein_selection] <= 0} {
        puts "WARNING: skipping SASA because selection is empty: $protein_selection"
        return
    }
    puts "Calculating SASA"
    set sel [atomselect top $protein_selection]
    set outfile [open [outpath "SASA_.dat"] w]
    for {set frame 0} {$frame < $nf} {incr frame} {
        molinfo top set frame $frame
        $sel frame $frame
        $sel update
        puts $outfile [measure sasa 1.4 $sel]
    }
    close $outfile
    $sel delete
}

proc calc_hbonds {} {
    global protein_selection
    if {[catch {package require hbonds} err]} {
        puts "WARNING: VMD hbonds plugin unavailable; skipping hbonds_.dat: $err"
        return
    }
    if {[selection_count $protein_selection] <= 0} {
        puts "WARNING: skipping hydrogen bonds because selection is empty: $protein_selection"
        return
    }
    puts "Calculating hydrogen bonds"
    set sel [atomselect top $protein_selection]
    if {[catch {hbonds -sel1 $sel -writefile yes -plot no -outfile [outpath "hbonds_.dat"]} err]} {
        puts "WARNING: hydrogen-bond calculation failed: $err"
    }
    $sel delete
}

proc calc_comcom {} {
    global protein_selection ligand_selection nf
    if {[selection_count $ligand_selection] <= 0} {
        puts "No ligand atoms found for '$ligand_selection'; skipping COM-COM"
        return
    }
    puts "Calculating protein-ligand COM-COM distance"
    set protein [atomselect top $protein_selection]
    set ligand [atomselect top $ligand_selection]
    set outfile [open [outpath "comcom_.dat"] w]
    for {set frame 0} {$frame < $nf} {incr frame} {
        $protein frame $frame
        $protein update
        $ligand frame $frame
        $ligand update
        set a [measure center $protein weight mass]
        set b [measure center $ligand weight mass]
        if {[catch {set box [lindex [pbc get -first $frame -last $frame] 0]} err]} {
            set box {}
        }
        if {[llength $box] >= 3 && [lindex $box 0] > 0 && [lindex $box 1] > 0 && [lindex $box 2] > 0} {
            set boxx [lindex $box 0]
            set boxy [lindex $box 1]
            set boxz [lindex $box 2]
            set dx [expr {[pmodulo [expr {[lindex $a 0] - [lindex $b 0] + ($boxx / 2.0)}] $boxx] - ($boxx / 2.0)}]
            set dy [expr {[pmodulo [expr {[lindex $a 1] - [lindex $b 1] + ($boxy / 2.0)}] $boxy] - ($boxy / 2.0)}]
            set dz [expr {[pmodulo [expr {[lindex $a 2] - [lindex $b 2] + ($boxz / 2.0)}] $boxz] - ($boxz / 2.0)}]
        } else {
            set dx [expr {[lindex $a 0] - [lindex $b 0]}]
            set dy [expr {[lindex $a 1] - [lindex $b 1]}]
            set dz [expr {[lindex $a 2] - [lindex $b 2]}]
        }
        set distance [expr {sqrt($dx * $dx + $dy * $dy + $dz * $dz)}]
        puts $outfile "$frame $distance"
    }
    close $outfile
    $protein delete
    $ligand delete
}

if {[catch {package require pbctools} err]} {
    puts "WARNING: pbctools unavailable; COM-COM will use direct distances only: $err"
}

load_system
align_to_protein_backbone

set protein_backbone "${protein_selection} and backbone"
set ligand_heavy "${ligand_selection} and noh"
set complex_selection "(${protein_selection} and backbone) or (${ligand_selection} and noh)"

calc_rmsd $protein_backbone "RMSD_apo_.dat"
calc_rmsf
calc_rog
calc_sasa
calc_hbonds

if {[selection_count $ligand_selection] > 0} {
    calc_rmsd $ligand_heavy "RMSD_.dat"
    calc_rmsd $complex_selection "RMSD_complex_.dat"
    calc_comcom
}

puts "VMD metric generation complete. Output directory: $metric_output_dir"
quit
"""

    replacements = {
        "__TOPOLOGY__": _tcl_double_quote(topology),
        "__TRAJECTORY__": _tcl_double_quote(trajectory),
        "__PROTEIN_SELECTION__": _tcl_double_quote(protein_selection),
        "__LIGAND_SELECTION__": _tcl_double_quote(ligand_selection),
        "__METRIC_OUTPUT_DIR__": _tcl_double_quote(metric_output_dir),
        "__MAX_FRAMES__": str(max_frames),
    }
    for placeholder, value in replacements.items():
        template = template.replace(placeholder, value)
    return template


def _tcl_double_quote(value: object) -> str:
    """Escape a Python value for use inside a Tcl double-quoted string."""
    text = str(value)
    return text.replace("\\", "\\\\").replace('"', '\\"')


def _build_mmpbsa_script(task: Dict) -> str:
    mpi_ranks = int(task.get("mpi_ranks", 24))
    input_file = task.get("input_file", "mmpbsa.in")
    structure = task.get("complex_tpr", "step5_production.tpr")
    topology = task.get("topology", "topol.top")
    index = task.get("index", "new_index.ndx")
    groups = task.get("groups", [21, 17])
    trajectory = task.get("trajectory", "step5_production_noPBC.xtc")

    if isinstance(groups, Iterable) and not isinstance(groups, str):
        group_text = " ".join(str(item) for item in groups)
    else:
        group_text = str(groups)

    return f"""#!/usr/bin/env bash
set -euo pipefail

# Generated helper. Review group IDs before running.
mpirun -np {mpi_ranks} gmx_MMPBSA MPI -O \\
  -i "{input_file}" \\
  -cs "{structure}" \\
  -cp "{topology}" \\
  -ci "{index}" \\
  -cg {group_text} \\
  -ct "{trajectory}"
"""


def _build_pca_script(task: Dict) -> str:
    gmx = task.get("gmx", "gmx")
    tpr = task.get("tpr", "step5_production.tpr")
    input_traj = task.get("trajectory", "step5_production.xtc")
    no_pbc = task.get("no_pbc_trajectory", "step5_production_noPBC.xtc")
    index = task.get("index", "new_index.ndx")
    output_dir = task.get("pca_dir", "PCA")
    fit_group = task.get("fit_group", "0")
    calpha_group = task.get("calpha_group", "0")

    return f"""#!/usr/bin/env bash
set -euo pipefail

# Generated helper. Replace group numbers if your index differs.
mkdir -p "{output_dir}"
echo q | {gmx} make_ndx -f step3_input.gro -o "{index}"
echo "{fit_group} 0" | {gmx} trjconv -f "{input_traj}" -o "{no_pbc}" -s "{tpr}" -pbc mol -center -n "{index}" -ur compact
echo "{calpha_group}" | {gmx} trjconv -f "{no_pbc}" -o "{output_dir}/step5_production_noPBC_Calpha.xtc" -n "{index}"
echo "{calpha_group}" | {gmx} trjconv -s "{tpr}" -f "{no_pbc}" -dump 0 -o "{output_dir}/ref.pdb" -n "{index}"
cd "{output_dir}"
echo "0 0" | {gmx} covar -mwa -ref -s ref.pdb -f step5_production_noPBC_Calpha.xtc -v eigenvectors_all_ref.trr -o eigenvals_all_ref.xvg
echo "0 0" | {gmx} anaeig -proj proj.xvg -first 1 -last 10 -s ref.pdb -f step5_production_noPBC_Calpha.xtc -v eigenvectors_all_ref.trr -eig eigenvals_all_ref.xvg
{gmx} analyze -n 10 -cc cc_all.xvg -f proj.xvg
echo "0 0" | {gmx} anaeig -s ref.pdb -f step5_production_noPBC_Calpha.xtc -2d 2dproj_12.xvg -first 1 -last 2 -v eigenvectors_all_ref.trr -eig eigenvals_all_ref.xvg
echo "0 0" | {gmx} anaeig -s ref.pdb -f step5_production_noPBC_Calpha.xtc -2d 2dproj_13.xvg -first 1 -last 3 -v eigenvectors_all_ref.trr -eig eigenvals_all_ref.xvg
echo "0 0" | {gmx} anaeig -s ref.pdb -f step5_production_noPBC_Calpha.xtc -2d 2dproj_23.xvg -first 2 -last 3 -v eigenvectors_all_ref.trr -eig eigenvals_all_ref.xvg
echo "0 0" | {gmx} anaeig -s ref.pdb -f step5_production_noPBC_Calpha.xtc -3d 3dproj_123.pdb -first 1 -last 3 -v eigenvectors_all_ref.trr -eig eigenvals_all_ref.xvg
"""
